version: '3.8'

services:
  web:
    build:
      context: .
    container_name: django_web
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=django_db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=Test1234
    stdin_open: true
    tty: true

  db:
    image: mysql:8.0
    container_name: my_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Test1234
      MYSQL_DATABASE: django_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: my_phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: Test1234
    ports:
      - '8080:80'

volumes:
  mysql_data:
