# Generated by Django 5.1.6 on 2025-02-21 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['-created_at'], 'verbose_name': 'Member'},
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['name'], name='member_name_726852_idx'),
        ),
        migrations.AlterModelTable(
            name='member',
            table='member',
        ),
    ]
