# Generated by Django 5.1.6 on 2025-02-26 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['completed']},
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='task_title_6e2cb8_idx',
        ),
        migrations.AlterModelTable(
            name='task',
            table=None,
        ),
    ]
