# Generated by Django 5.1.6 on 2025-02-26 05:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_task_options_remove_task_task_title_6e2cb8_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['completed'], 'verbose_name': 'Task'},
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['title'], name='task_title_6e2cb8_idx'),
        ),
        migrations.AlterModelTable(
            name='task',
            table='task',
        ),
    ]
